Repository IHateMyKite/UnforgivingDevices, pull requests merged in 2023-04, with the labels that each got.

#136 Hobble fixes
  Scripts/Source/UDCustomDeviceMain.psc
  Scripts/Source/UD_CustomArmCuffs_RenderScript.psc
  Scripts/Source/UD_CustomDevice_EquipScript.psc
  Scripts/Source/UD_CustomDynamicHeavyBondage_RS.psc
  Scripts/Source/UD_CustomLegCuffs_RenderScript.psc
Labels: bug

#134 Minigame duration adjustments
  Scripts/Source/UDCustomDeviceMain.psc
  Scripts/Source/UD_CustomDevice_NPCSlot.psc
  Scripts/Source/UD_CustomDevice_RenderScript.psc
  Scripts/Source/UD_MCM_script.psc
  interface/translations/UnforgivingDevices_CHINESE.txt
  interface/translations/UnforgivingDevices_CZECH.txt
  interface/translations/UnforgivingDevices_ENGLISH.txt
  interface/translations/UnforgivingDevices_FRENCH.txt
  interface/translations/UnforgivingDevices_GERMAN.txt
  interface/translations/UnforgivingDevices_ITALIAN.txt
  interface/translations/UnforgivingDevices_JAPANESE.txt
  interface/translations/UnforgivingDevices_POLISH.txt
  interface/translations/UnforgivingDevices_RUSSIAN.txt
  interface/translations/UnforgivingDevices_SPANISH.txt
Labels: enhancement

#144 Prototype: Reworked init of many modules
  PR144_InitProto.esp
  Scripts/Source/UDCustomDeviceMain.psc
  Scripts/Source/UD_AnimationManagerScript.psc
  Scripts/Source/UD_CompatibilityManager_Script.psc
  Scripts/Source/UD_CustomDevice_NPCSlot.psc
  Scripts/Source/UD_CustomDevices_NPCSlotsManager.psc
  Scripts/Source/UD_DialogueMain.psc
  Scripts/Source/UD_ExpressionManager.psc
  Scripts/Source/UD_LeveledList_Patcher.psc
  Scripts/Source/UD_MCM_script.psc
  Scripts/Source/UD_MenuChecker.psc
  Scripts/Source/UD_ModifierManager_Script.psc
  Scripts/Source/UD_NPCInteligence.psc
  Scripts/Source/UD_OrgasmManager.psc
  Scripts/Source/UD_OrgasmUpdater.psc
  Scripts/Source/UD_RandomRestraintManager.psc
  Scripts/Source/UD_WidgetControl.psc
  Scripts/Source/UnforgivingDevicesMain.psc
  Scripts/Source/zadBoundCombatScript_UDPatch.psc
  Scripts/Source/zadlibs_UDPatch.psc
Labels: bug

#149 UDAM & UDWC docu
  Scripts/Source/UD_API.psc
  Scripts/Source/UD_AnimationManagerScript.psc
  Scripts/Source/UD_CustomDevice_RenderScript.psc
  Scripts/Source/UD_MCM_script.psc
  Scripts/Source/UD_WidgetControl.psc
Labels: documentation

#148 Documentation of UD_CustomDevice_RenderScript
  Scripts/Source/UDCustomDeviceMain.psc
  Scripts/Source/UD_AbadonPlug_RenderScript.psc
  Scripts/Source/UD_ControlablePlug_RenderScript.psc
  Scripts/Source/UD_CustomDevice_NPCSlot.psc
  Scripts/Source/UD_CustomDevice_RenderScript.psc
  Scripts/Source/UD_CustomDevices_NPCSlotsManager.psc
  Scripts/Source/UD_CustomDynamicHeavyBondage_RS.psc
  Scripts/Source/UD_CustomInflatablePlug_RenderScript.psc
  Scripts/Source/UD_CustomPanelGag_RenderScript.psc
  Scripts/Source/UD_CustomPlug_RenderScript.psc
  Scripts/Source/UD_CustomSuit_RenderScript.psc
  Scripts/Source/UD_OrgasmManager.psc
  Scripts/Source/UD_ParalelProcess.psc
  docs/RenderDeviceTemplate.psc
Labels: documentation
