Repository IHateMyKite/UnforgivingDevices, pull requests merged in 2023-01, with the labels that each got.

#112 all done
  Scripts/Source/UD_AbadonPlug_RenderScript.psc
  Scripts/Source/UD_BlackGooMagEffect_Script.psc
  Scripts/Source/UD_ConcBlackGoo_AME.psc
  Scripts/Source/UD_CursedGoo_AME.psc
  Scripts/Source/UD_MCM_script.psc
  Scripts/Source/UD_PurifiedGoo_AME.psc
  Scripts/Source/UD_TrapManifest_ME_Script.psc
  Scripts/Source/UnforgivingDevicesMain.psc
Labels: enhancement, Compatibility

#92 Using group animation when struggling out of DD with helper
  .gitignore
  PR92_UnforgivingDevices.esp
  Scripts/Source/UDCustomDeviceMain.psc
  Scripts/Source/UD_AbadonQuest_script.psc
  Scripts/Source/UD_AbadonWeapon_AME.psc
  Scripts/Source/UD_AnimationManagerScript.psc
  Scripts/Source/UD_BlackGooBallScript.psc
  Scripts/Source/UD_ConcBlackGoo_AME.psc
  Scripts/Source/UD_CustomArmCuffs_RenderScript.psc
  Scripts/Source/UD_CustomBlindfold_RenderScript.psc
  Scripts/Source/UD_CustomDeviceExhaustion_MagEffect.psc
  Scripts/Source/UD_CustomDevice_EquipScript.psc
  Scripts/Source/UD_CustomDevice_NPCSlot.psc
  Scripts/Source/UD_CustomDevice_RenderScript.psc
  Scripts/Source/UD_CustomDevices_NPCSlotsManager.psc
  Scripts/Source/UD_CustomDynamicHeavyBondage_RS.psc
  Scripts/Source/UD_CustomGag_RenderScript.psc
  Scripts/Source/UD_CustomHood_RenderScript.psc
  Scripts/Source/UD_CustomLegCuffs_RenderScript.psc
  Scripts/Source/UD_CustomVibratorBase_RenderScript.psc
  Scripts/Source/UD_GlobalVariables.psc
  Scripts/Source/UD_MCM_script.psc
  Scripts/Source/UD_NPCInteligence.psc
  Scripts/Source/UD_OrgasmExhaustion_AME.psc
  Scripts/Source/UD_OrgasmManager.psc
  Scripts/Source/UD_OrgasmManagerPlayer.psc
  Scripts/Source/UD_OrgasmUpdater.psc
  Scripts/Source/UD_ParalelProcess.psc
  Scripts/Source/UD_PlayerSlotScript.psc
  Scripts/Source/UD_TrapManifest_ME_Script.psc
  Scripts/Source/UnforgivingDevicesMain.psc
  Scripts/Source/zadlibs_UDPatch.psc
  docs/UD Paired Struggle.xls
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_BakaFactory.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_Billyy_Human.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_Billyy_HumanFuta.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_Billyy_HumanLesbian.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_DD.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_Leito.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_Leito_Aggr.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_SexLab.json
  skse/plugins/StorageUtilData/UD/Animations/UDStruggle_DB_ZaZ.json
Labels: enhancement

#116 Added lock durability
  PR116_LockRework2.esp
  Scripts/Source/UDCustomDeviceMain.psc
  Scripts/Source/UD_CustomDevice_RenderScript.psc
  Scripts/Source/UD_MCM_script.psc
  Scripts/Source/UD_UIEListMenu.psc
  Scripts/Source/UnforgivingDevicesMain.psc
Labels: bug, enhancement

#119 Update UD_MCM_script.psc
  Scripts/Source/UD_MCM_script.psc
Labels: bug
